services:
  redis:
    image: ${REDIS_IMAGE}
    container_name: redis
    ports: 
    - "6379:6379"

  mysql:
    image: ${MYSQL_IMAGE}
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: ${RABBITMQ_IMAGE}
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rmquser
      RABBITMQ_DEFAULT_PASS: rmqpass
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network


volumes:
  mysql_data:
  rabbitmq_data:

networks:
  app-network:

